### ISSUE TITLE
Video 

### ISSUE THREAD

**Issue by Aleksandrt6** [KobeW50/ReVanced-Documentation#6]
### Question

video play load and buffer and  doesn't want to work , please your assistance. Uninstall to dislocated explicitly language.
![Screenshot_20240817_114727_IntentResolver](https://github.com/user-attachments/assets/42db095e-72c9-4ca1-97ad-7bd88ad8a6b0)

### Acknowledgements

- [X] All requested information has been provided properly.
- [X] I have chosen an appropriate title.

**Comment by KobeW50** [comment]
Oepn YT ReVanced > Settings > ReVanced > Miscellaneous > Spoof client > Spoof client, ON.

If you have further issues, please ask in one of the ReVanced support channels. This repository does not have any guides for YouTube ReVanced.
